### ISSUE TITLE
TYT MD2017 konffi

### ISSUE THREAD

**Issue by jwwallin** [lasselehtinen/oh-repeaters-dmrconfig#2]
Moi,

tein omaan MD2017 tuon sinun konffisi pohjalta oman konffin. Miten suhtaudut mahdollisiin pullareihin?

**Comment by lasselehtinen** [comment]
Hei,

PR:iä saa totta kai tehdä. Kannattaa tosiaan huomioida että tämän on tarkoitus olla mahdollisimman geneerinen config. Mutta jos esim. itse tiedoissa on jotakin virheitä, korjaukset ovat toki tervetulleita.

**Comment by jwwallin** [comment]
OK. Katsotaan miten tuo minun tekemäni konffi toimii ja laitan sitten PR:ää, jos koen sen tarpeeksi yleishyödylliseksi. Arvioidaan tilanne sitten uudestaan.
